services:
  ui:
    build: ui
    ports:
      - "80:80"
    restart: unless-stopped
  server:
    build: server
    privileged: true
    volumes:
      - ./server/config:/app/config
    restart: unless-stopped
