services:
  ui:
    image: ghcr.io/andresrobam/brew/ui:latest
    network_mode: host
    ports:
      - "80:80"
    restart: unless-stopped
  server:
    image: ghcr.io/andresrobam/brew/server:latest
    privileged: true
    restart: unless-stopped
