name: Build UI
env:
  IMAGE: ghcr.io/${{ github.repository }}/ui:latest
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Build static files for UI
        run: |
          cd ${{ github.workspace }}/ui
          bun install
          bun run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "${{ github.workspace }}/ui"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE }}
