name: Build
env:
  IMAGE: brew-ui:latest
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to docker registry
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build static files for UI
        uses: oven-sh/setup-bun@v2
        uses: actions/checkout@v4
      - run: cd ui
      - run: bun run build
      - name: Build docker image
        uses: actions/checkout@v4
      - run: cd ../docker
      - run: docker build . --tag $IMAGE
      - name: Push docker image
      - run: docker push $IMAGE