name: Build UI
env:
  IMAGE: brew-ui:latest
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Checkout the repository
        uses: actions/checkout@v4
        
      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Build static files for UI
        run: |
          cd ${{ github.workspace }}/ui
          bun install
          bun run build

      - name: Build docker image
        run: |
          cd ${{ github.workspace }}/ui
          docker build . --tag $IMAGE
      
      - name: Push docker image
        run: docker push $IMAGE